Traceback (most recent call last):
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/matthewmckay/anaconda3/envs/jupyterbook-latest/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (11, 5)  #set default figure size
import numpy as np
from quantecon import LinearStateSpace
from scipy.stats import norm
import random
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-2-d95733a4c1e1>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mplt[0m[0;34m.[0m[0mrcParams[0m[0;34m[[0m[0;34m"figure.figsize"[0m[0;34m][0m [0;34m=[0m [0;34m([0m[0;36m11[0m[0;34m,[0m [0;36m5[0m[0;34m)[0m  [0;31m#set default figure size[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mquantecon[0m [0;32mimport[0m [0mLinearStateSpace[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;32mfrom[0m [0mscipy[0m[0;34m.[0m[0mstats[0m [0;32mimport[0m [0mnorm[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mrandom[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'quantecon'
ModuleNotFoundError: No module named 'quantecon'

